Twirp:
  Enabled: true

Twirp/ClientResponse:
  Description: 'Use webmock-twirp to stub client responses'
  Enabled: true
  VersionAdded: '0.1'

Twirp/DeprecatedArguments:
  Description: 'Use keyword args for `Twirp::ClientResp.new`'
  Enabled: false
  VersionAdded: '0.1'
  Severity: error

Twirp/RSpecBeA:
  Description: 'Use rspec-twirp to simplify specs'
  Enabled: true
  VersionAdded: '0.1'
